from django.urls import path
from inventory import views
from inventory.views import *


urlpatterns = [
    path('device/multiple/create', views.create_multiple_device, name='create_multiple_device'),
    path('device/create', DeviceCreateView.as_view(), name='create_device'),
    path('device/province/create', DeviceProvinceCreateView.as_view(), name='create_device_province'),
    path('device/type/create', DeviceTypeCreateView.as_view(), name='create_device_type'),
    path('device/category/create', DeviceCategoryCreateView.as_view(), name='create_device_category'),
    path('device/vendor/create', DeviceVendorCreateView.as_view(), name='create_device_vendor'),
    path('device/os/create', DeviceOSCreateView.as_view(), name='create_device_os'),
    path('device/firmware/create', DeviceFirmwareCreateView.as_view(), name='create_device_firmware'),
    path('device/management/create', DeviceManagementCreateView.as_view(), name='create_device_management'),
    path('device/rack-layout/create', DeviceRackLayoutCreateView.as_view(), name='create_device_rack_layout'),
    path('device/branch/create', DeviceBranchCreateView.as_view(), name='create_device_branch'),
    path('device/group/create', DeviceGroupCreateView.as_view(), name='create_device_group'),
    path('device/group', DeviceGroupListView.as_view(), name='list_device_group'),
    path('device/group/update/<int:pk>', DeviceGroupUpdateView.as_view(), name='update_device_group'),
    path('device/group/delete/<int:pk>', DeviceGroupDeleteView.as_view(), name='delete_device_group'),
    path('device/province', DeviceProvinceListView.as_view(), name='list_device_province'),
    path('device/province/update/<int:pk>', DeviceProvinceUpdateView.as_view(), name='update_device_province'),
    path('device/province/delete/<int:pk>', DeviceProvinceDeleteView.as_view(), name='delete_device_province'),
    path('device/branch', DeviceBranchListView.as_view(), name='list_device_branch'),
    path('device/branch/update/<int:pk>', DeviceBranchUpdateView.as_view(), name='update_device_branch'),
    path('device/branch/delete/<int:pk>', DeviceBranchDeleteView.as_view(), name='delete_device_branch'),
    path('device/type', DeviceTypeListView.as_view(), name='list_device_type'),
    path('device/type/update/<int:pk>', DeviceTypeUpdateView.as_view(), name='update_device_type'),
    path('device/type/delete/<int:pk>', DeviceTypeDeleteView.as_view(), name='delete_device_type'),
    path('device/category', DeviceCategoryListView.as_view(), name='list_device_category'),
    path('device/category/update/<int:pk>', DeviceCategoryUpdateView.as_view(), name='update_device_category'),
    path('device/category/delete/<int:pk>', DeviceCategoryDeleteView.as_view(), name='delete_device_category'),
    path('device/vendor', DeviceVendorListView.as_view(), name='list_device_vendor'),
    path('device/vendor/update/<int:pk>', DeviceVendorUpdateView.as_view(), name='update_device_vendor'),
    path('device/vendor/delete/<int:pk>', DeviceVendorDeleteView.as_view(), name='delete_device_vendor'),
    path('device/os', DeviceOSListView.as_view(), name='list_device_os'),
    path('device/os/update/<int:pk>', DeviceOSUpdateView.as_view(), name='update_device_os'),
    path('device/os/delete/<int:pk>', DeviceOSDeleteView.as_view(), name='delete_device_os'),
    path('device/firmware', DeviceFirmwareListView.as_view(), name='list_device_firmware'),
    path('device/firmware/update/<int:pk>', DeviceFirmwareUpdateView.as_view(), name='update_device_firmware'),
    path('device/firmware/delete/<int:pk>', DeviceFirmwareDeleteView.as_view(), name='delete_device_firmware'),
    path('device', DeviceListView.as_view(), name='list_device'),
    path('device/delete/<int:pk>', DeviceDeleteView.as_view(), name='delete_device'),
    path('device/update/<int:pk>', DeviceUpdateView.as_view(), name='update_device'),
    path('device/detail/<int:pk>', DeviceDetailView.as_view(), name='detail_device'),
    path('device/management', DeviceManagementListView.as_view(), name='list_device_management'),
    path('device/management/update/<int:pk>', DeviceManagementUpdateView.as_view(), name='update_device_management'),
    path('device/management/detail/<int:pk>', DeviceManagementDetailView.as_view(), name='detail_device_management'),
    path('device/management/delete/<int:pk>', DeviceManagementDeleteView.as_view(), name='delete_device_management'),
    path('device/rack-layout', DeviceRackLayoutListView.as_view(), name='list_device_rack_layout'),
    path('device/rack-layout/update/<int:pk>', DeviceRackLayoutUpdateView.as_view(), name='update_device_rack_layout'),
    path('device/rack-layout/detail/<int:pk>', DeviceRackLayoutDetailView.as_view(), name='detail_device_rack_layout'),
    path('device/rack-layout/delete/<int:pk>', DeviceRackLayoutDeleteView.as_view(), name='delete_device_rack_layout'),
    path('device/dashboard', views.device_dashboard, name='device_dashboard'),
    path('device/export', views.device_export, name='device_export')
]

