# Generated by Django 5.1.6 on 2025-07-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointEmailAlertTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=500)),
                ('email_title', models.CharField(max_length=500)),
                ('email_body', models.CharField(max_length=3000)),
            ],
        ),
    ]
