# Generated by Django 5.2 on 2025-07-19 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointlocaluser',
            name='template',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='cm.checkpointlocalusertemplate'),
            preserve_default=False,
        ),
    ]
