# Generated by Django 5.2 on 2025-05-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0002_checkpointgateway_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmcdomain',
            name='domain',
            field=models.CharField(max_length=500),
        ),
    ]
