# Generated by Django 5.1.7 on 2025-07-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0002_checkpointlocaluser_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpointlocaluser',
            name='site',
        ),
    ]
