# Generated by Django 5.2 on 2025-07-19 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0002_alter_checkpointlocaluser_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointlocaluser',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.checkpointlocalusertemplate'),
        ),
        migrations.AlterField(
            model_name='checkpointlocaluser',
            name='user_group',
            field=models.ManyToManyField(blank=True, to='cm.checkpointlocalusergroup'),
        ),
    ]
