# Generated by Django 5.1.6 on 2025-07-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0002_checkpointemailalerttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointemailalerttemplate',
            name='template_name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
