# Generated by Django 5.1.6 on 2025-05-20 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0003_alter_fmcdomain_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fmcpolicy',
            name='gateway',
        ),
        migrations.AddField(
            model_name='fmcgateway',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.fmcpolicy'),
        ),
        migrations.AddField(
            model_name='fmcpolicy',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.fmcsite'),
        ),
    ]
