# Generated by Django 5.2 on 2025-07-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0003_alter_checkpointlocaluser_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointemailalerttemplate',
            name='email_body',
            field=models.CharField(max_length=5000),
        ),
    ]
