# Generated by Django 5.1.6 on 2025-05-27 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0003_alter_fmcdomain_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fmcgateway',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='fmcpolicy',
            name='gateway',
        ),
        migrations.AddField(
            model_name='checkpointsite',
            name='smc_hostname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fmcgateway',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.fmcpolicy'),
        ),
        migrations.AddField(
            model_name='fmcpolicy',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.fmcdomain'),
        ),
        migrations.CreateModel(
            name='CheckpointLocalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(default=0)),
                ('expiration_date', models.CharField(max_length=200)),
                ('user_created', models.CharField(max_length=200)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Created', max_length=200)),
                ('message', models.CharField(blank=True, max_length=3000, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.checkpointsite')),
            ],
        ),
    ]
