# Generated by Django 5.1.6 on 2025-05-20 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0004_remove_fmcpolicy_gateway_fmcgateway_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fmcpolicy',
            name='site',
        ),
    ]
