# Generated by Django 5.1.6 on 2025-08-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0004_alter_checkpointemailalerttemplate_email_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointlocalusertemplate',
            name='vpn_gateway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkpointlocalusertemplate',
            name='vpn_policy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
