# Generated by Django 5.1.7 on 2025-07-04 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0004_remove_checkpointlocalusertemplate_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointlocalusertemplate',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cm.checkpointsite'),
            preserve_default=False,
        ),
    ]
