# Generated by Django 5.1.6 on 2025-05-27 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0004_remove_fmcgateway_domain_remove_fmcpolicy_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointsite',
            name='radius_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CheckpointLocalUserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('radius_group_server', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.checkpointsite')),
            ],
        ),
    ]
