# Generated by Django 5.1.6 on 2025-05-27 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0005_checkpointsite_radius_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpointlocaluser',
            name='site',
        ),
        migrations.AddField(
            model_name='checkpointlocaluser',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.checkpointlocalusertemplate'),
        ),
    ]
