# Generated by Django 5.1.6 on 2025-05-20 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0005_remove_fmcpolicy_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fmcgateway',
            name='domain',
        ),
        migrations.AddField(
            model_name='fmcpolicy',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.fmcdomain'),
        ),
    ]
