# Generated by Django 5.1.6 on 2025-05-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0006_remove_fmcgateway_domain_fmcpolicy_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointLocalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(default=0)),
                ('expiration_date', models.CharField(max_length=200)),
                ('user_created', models.CharField(max_length=200)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Created', max_length=200)),
                ('message', models.CharField(blank=True, max_length=3000, null=True)),
                ('smc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.checkpointsite')),
            ],
        ),
    ]
