# Generated by Django 5.2 on 2025-05-27 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0006_remove_fmcgateway_domain_fmcpolicy_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointsite',
            name='radius_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkpointsite',
            name='smc_hostname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CheckpointLocalUserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('radius_group_server', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.checkpointsite')),
            ],
        ),
        migrations.CreateModel(
            name='CheckpointLocalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(default=0)),
                ('expiration_date', models.CharField(max_length=200)),
                ('user_created', models.CharField(max_length=200)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Created', max_length=200)),
                ('message', models.CharField(blank=True, max_length=3000, null=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.checkpointlocalusertemplate')),
            ],
        ),
    ]
