# Generated by Django 5.2 on 2025-05-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0007_checkpointsite_radius_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpointsite',
            name='radius_group',
        ),
    ]
