# Generated by Django 5.1.6 on 2025-05-28 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0008_remove_checkpointsite_radius_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointlocalusertemplate',
            name='default_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CheckpointLocalUSerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.checkpointsite')),
            ],
        ),
        migrations.AddField(
            model_name='checkpointlocaluser',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.checkpointlocalusergroup'),
        ),
    ]
