# Generated by Django 5.1.6 on 2025-05-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0009_checkpointlocalusertemplate_default_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointlocaluser',
            name='custom_group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
