# Generated by Django 5.1.6 on 2025-05-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0010_checkpointlocaluser_custom_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpointlocaluser',
            name='user_group',
        ),
        migrations.AddField(
            model_name='checkpointlocaluser',
            name='user_group',
            field=models.ManyToManyField(blank=True, null=True, to='cm.checkpointlocalusergroup'),
        ),
    ]
