# Generated by Django 5.1.6 on 2025-05-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0011_remove_checkpointlocaluser_user_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointlocaluser',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
    ]
