# Generated by Django 5.1.6 on 2025-06-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0012_checkpointlocaluser_is_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointlocaluser',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checkpointlocaluser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
