# Generated by Django 5.1.6 on 2025-06-28 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0013_alter_checkpointlocaluser_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpointlocalusertemplate',
            name='site',
        ),
        migrations.AddField(
            model_name='checkpointlocaluser',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cm.checkpointsite'),
        ),
    ]
