# Generated by Django 5.1.6 on 2025-07-01 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0014_remove_checkpointlocalusertemplate_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpointlocaluser',
            name='site',
        ),
        migrations.AddField(
            model_name='checkpointlocalusertemplate',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cm.checkpointsite'),
            preserve_default=False,
        ),
    ]
