# Generated by Django 5.1.6 on 2025-07-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0015_remove_checkpointlocaluser_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointlocaluser',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
