# Generated by Django 5.1.6 on 2025-07-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0016_alter_checkpointlocaluser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointlocalusertemplate',
            name='skip_send_alert_email',
            field=models.BooleanField(default=False),
        ),
    ]
