from django.urls import path
from cm import views
from cm.views import *


urlpatterns = [
    path("checkpoint/access-rule/create",CheckpointRuleView.as_view(),name="checkpoint_create_task_access_rule"),
    path("checkpoint/access-rule/list",CheckpointRuleListView.as_view(),name="checkpoint_list_task_access_rule"),
    path("checkpoint/access-rule/delete/<int:pk>",CheckpointRuleDeleteView.as_view(),name="checkpoint_delete_task_access_rule"),
    path("checkpoint/access-rule/detail/<int:pk>",CheckpointRuleDetailView.as_view(),name="checkpoint_detail_task_access_rule"),
    path("checkpoint/access-rule/update/<int:pk>",CheckpointRuleUpdateView.as_view(),name="checkpoint_update_task_access_rule"),
    path("checkpoint/policy/create",CheckpointPolicyCreateView.as_view(),name="checkpoint_create_policy"),
    path("checkpoint/policy/list",CheckpointPolicyListView.as_view(),name="checkpoint_list_policy"),
    path("checkpoint/policy/update/<int:pk>",CheckpointPolicyUpdateView.as_view(),name="checkpoint_update_policy"),
    path("checkpoint/policy/delete/<int:pk>",CheckpointPolicyDeleteView.as_view(),name="checkpoint_delete_policy"),
    path("checkpoint/gateway/create",CheckpointGatewayCreateView.as_view(),name="checkpoint_create_gateway"),
    path("checkpoint/gateway/list",CheckpointGatewayListView.as_view(),name="checkpoint_list_gateway"),
    path("checkpoint/gateway/update/<int:pk>",CheckpointGatewayUpdateView.as_view(),name="checkpoint_update_gateway"),
    path("checkpoint/gateway/delete/<int:pk>",CheckpointGatewayDeleteView.as_view(),name="checkpoint_delete_gateway"),
    path("checkpoint/site/create",CheckpointSiteCreateView.as_view(),name="checkpoint_create_site"),
    path("checkpoint/site/list",CheckpointSiteListView.as_view(),name="checkpoint_list_site"),
    path("checkpoint/site/update/<int:pk>",CheckpointSiteUpdateView.as_view(),name="checkpoint_update_site"),
    path("checkpoint/site/delete/<int:pk>",CheckpointSiteDeleteView.as_view(),name="checkpoint_delete_site"),
    path("checkpoint/dashboard",views.checkpoint_dashboard,name="checkpoint_dashboard"),
    path("f5/device/list", F5DeviceListView.as_view(), name="f5_list_device"),
    path("f5/device/create", F5DeviceCreateView.as_view(), name="f5_create_device"),
    path("f5/device/update/<int:pk>",F5DeviceUpdateView.as_view(),name="f5_update_device"),
    path("f5/device/delete/<int:pk>",F5DeviceDeleteView.as_view(),name="f5_delete_device"),
    path("f5/tasks/virtual-server/create",F5CreateVirtualServerCreateView.as_view(),name="f5_create_virtual_server"),
    path("f5/tasks/limit-connection/create",F5LimitConnectionCreateView.as_view(),name="f5_create_limit_connection"),
    path("f5/permission/list",F5VirtualServerPermissionListView.as_view(),name="f5_list_permission"),
    path("f5/permission/update/<int:pk>",F5VirtualServerPermissionUpdateView.as_view(),name="f5_update_permission"),
    path("f5/virtual-server/list",F5VirtualServerListView.as_view(),name="f5_list_virtual_server"),
    path("f5/virtual-server/update/<int:pk>",F5VirtualServerUpdateView.as_view(),name="f5_update_virtual_server"),
    path("f5/virtual-server/update/multiple",views.f5_update_multiple_virtual_server,name="f5_update_multiple_virtual_server"),
    path("f5/export", views.f5_database_export, name='f5_export_database'),
    path("f5/virtual-server/delete/<int:pk>",F5VirtualServerDeleteView.as_view(),name="f5_delete_virtual_server"),
    path("f5/tasks/list", F5TaskListView.as_view(), name="f5_list_task"),
    path("f5/tasks/update/<str:task_name>/<int:task_id>",F5TaskUpdateView.as_view(),name="f5_update_task"),
    path("f5/tasks/delete/<str:task_name>/<int:task_id>",F5TaskDeleteView.as_view(),name="f5_delete_task"),
    path("f5/template/list", F5TemplateListView.as_view(), name="f5_list_template"),
    path("f5/template/create", F5TemplateCreateView.as_view(), name="f5_create_template"),
    path("f5/template/detail/<int:pk>",F5TemplateDetailView.as_view(),name="f5_detail_template"),
    path("f5/template/update/<int:pk>",F5TemplateUpdateView.as_view(),name="f5_update_template"),
    path("f5/template/delete/<int:pk>",F5TemplateDeleteView.as_view(),name="f5_delete_template"),
    path("fmc/access-rule/create",FMCRuleView.as_view(),name="fmc_create_task_access_rule"),
    path("fmc/access-rule/list",FMCRuleListView.as_view(),name="fmc_list_task_access_rule"),
    path("fmc/access-rule/delete/<int:pk>",FMCRuleDeleteView.as_view(),name="fmc_delete_task_access_rule"),
    path("fmc/access-rule/detail/<int:pk>",FMCRuleDetailView.as_view(),name="fmc_detail_task_access_rule"),
    path("fmc/access-rule/update/<int:pk>",FMCRuleUpdateView.as_view(),name="fmc_update_task_access_rule"),
    path("fmc/policy/create",FMCPolicyCreateView.as_view(),name="fmc_create_policy"),
    path("fmc/policy/list",FMCPolicyListView.as_view(),name="fmc_list_policy"),
    path("fmc/policy/update/<int:pk>",FMCPolicyUpdateView.as_view(),name="fmc_update_policy"),
    path("fmc/policy/delete/<int:pk>",FMCPolicyDeleteView.as_view(),name="fmc_delete_policy"),
    path("fmc/gateway/create",FMCGatewayCreateView.as_view(),name="fmc_create_gateway"),
    path("fmc/gateway/list",FMCGatewayListView.as_view(),name="fmc_list_gateway"),
    path("fmc/gateway/update/<int:pk>",FMCGatewayUpdateView.as_view(),name="fmc_update_gateway"),
    path("fmc/gateway/delete/<int:pk>",FMCGatewayDeleteView.as_view(),name="fmc_delete_gateway"),
    path("fmc/site/create",FMCSiteCreateView.as_view(),name="fmc_create_site"),
    path("fmc/site/list",FMCSiteListView.as_view(),name="fmc_list_site"),
    path("fmc/site/update/<int:pk>",FMCSiteUpdateView.as_view(),name="fmc_update_site"),
    path("fmc/site/delete/<int:pk>",FMCSiteDeleteView.as_view(),name="fmc_delete_site"),
    path("fmc/dashboard",views.fmc_dashboard,name="fmc_dashboard")
]
