# Generated by Django 5.2 on 2025-05-17 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_branch', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_category', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_group', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_os', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_province', models.CharField(max_length=200, unique=True, verbose_name='P&L')),
                ('description', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_vendor', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200)),
                ('device_ip', models.GenericIPAddressField(unique=True)),
                ('device_firmware', models.CharField(blank=True, max_length=200)),
                ('device_status', models.CharField(blank=True, max_length=200)),
                ('device_stack', models.BooleanField(default=False)),
                ('device_description', models.CharField(blank=True, max_length=200)),
                ('device_creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(blank=True, max_length=100)),
                ('device_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.devicebranch')),
                ('device_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.devicecategory')),
                ('device_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.devicegroup')),
                ('device_os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.deviceos')),
                ('device_province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.deviceprovince')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.devicetype')),
                ('device_vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.devicevendor')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_serial_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('start_ma_date', models.DateField(blank=True, null=True)),
                ('end_ma_date', models.DateField(blank=True, null=True)),
                ('start_license_date', models.DateField(blank=True, null=True)),
                ('end_license_date', models.DateField(blank=True, null=True)),
                ('end_sw_support_date', models.DateField(blank=True, null=True)),
                ('end_hw_support_date', models.DateField(blank=True, null=True)),
                ('start_used_date', models.DateField(blank=True, null=True)),
                ('user_created', models.CharField(blank=True, max_length=100, null=True)),
                ('device_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceRackLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_rack_name', models.CharField(blank=True, max_length=200)),
                ('device_rack_unit', models.CharField(blank=True, max_length=200)),
                ('user_created', models.CharField(blank=True, max_length=100)),
                ('device_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device')),
                ('device_serial_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.devicemanagement')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceFirmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmware', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(blank=True, max_length=100)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.devicetype')),
            ],
        ),
    ]
