# Generated by Django 5.2 on 2025-05-17 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('vlan', models.IntegerField(blank=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipplan.region')),
            ],
        ),
        migrations.CreateModel(
            name='IpAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('inused', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipplan.subnet')),
            ],
        ),
        migrations.CreateModel(
            name='SubnetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=200, unique=True)),
                ('group_subnet', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipplan.location')),
            ],
        ),
        migrations.AddField(
            model_name='subnet',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipplan.subnetgroup'),
        ),
    ]
