from django.urls import path
from api import views
from api.views import *


urlpatterns = [
    path("inventory/dashboard-01", views.inventory_dashboard_01),
    path("inventory/dashboard-02", views.inventory_dashboard_02),
    path("inventory/dashboard-04", views.inventory_dashboard_04),
    path("inventory/dashboard-05", views.inventory_dashboard_05),
    path("inventory/dashboard-06", views.inventory_dashboard_06),
    path("inventory/dashboard-07", views.inventory_dashboard_07),
    path("cm/checkpoint/dashboard-01", views.checkpoint_dashboard_01),
    path("cm/checkpoint/dashboard-02", views.checkpoint_dashboard_02),
    path("inventory/device", views.get_list_device),
    path("inventory/update/device-firmware", views.update_device_firmware),
    path("inventory/update/device-status", views.update_device_status),
    path("inventory/report", views.inventory_report),
    path("ipplan/dashboard-01", views.ipplan_dashboard_01),
    path("ipplan/dashboard-02", views.ipplan_dashboard_02),
    path("ipplan/dashboard-03", views.ipplan_dashboard_03),
    path("ipplan/ipaddress", views.ipplan_get_list_ip_available),
    path("ipplan/subnet", views.ipplan_get_list_subnet),
    path("ipplan/update/ipaddress", views.ipplan_update_ip_status),
    path("cm/checkpoint/create-rule", views.cm_checkpoint_create_rule),
    path("cm/checkpoint/policy", views.cm_checkpoint_get_list_policy),
    path("cm/checkpoint/rule", views.cm_checkpoint_get_list_rule),
    path("cm/checkpoint/update/rule-status", views.cm_checkpoint_update_rule_status),
    path("cm/checkpoint/update/rule-section", views.cm_checkpoint_update_rule_section),
    path("cm/checkpoint/section", views.cm_checkpoint_get_list_rule_section),
    path("cm/checkpoint/site", views.cm_checkpoint_get_list_site),
    path("cm/checkpoint/update/local-user-group", views.cm_checkpoint_update_local_user_group),
    path("cm/checkpoint/gateway", views.cm_checkpoint_get_list_gateway),
    path("cm/checkpoint/local-user", views.cm_checkpoint_get_list_local_user),
    path("cm/checkpoint/update/local-user", views.cm_checkpoint_update_local_user),
    path("cm/checkpoint/alert-email-template", views.cm_checkpoint_get_alert_email_template),
    path("cm/f5/get/device", views.cm_f5_get_list_device),
    path("cm/f5/get/client-ssl-profile", views.cm_f5_get_list_client_ssl_profile),
    path("cm/f5/get/server-ssl-profile", views.cm_f5_get_list_server_ssl_profile),
    path("cm/f5/get/template", views.cm_f5_get_list_template),
    path("cm/f5/get/waf-profile", views.cm_f5_get_list_waf_profile),
    path("cm/f5/get/irule-profile", views.cm_f5_get_list_irule_profile),
    path("cm/f5/get/virtual-server", views.cm_f5_get_list_virtual_server),
    path("cm/f5/get/pool-monitor", views.cm_f5_get_list_pool_monitor),
    path("cm/f5/get/pool-lb-method", views.cm_f5_get_list_pool_lb_method),
    path("cm/f5/update/client-ssl-profile", views.cm_f5_update_client_ssl_profile),
    path("cm/f5/update/server-ssl-profile", views.cm_f5_update_server_ssl_profile),
    path("cm/f5/update/irule-profile", views.cm_f5_update_irule_profile),
    path("cm/f5/update/waf-profile", views.cm_f5_update_waf_profile),
    path("cm/f5/update/pool-monitor", views.cm_f5_update_pool_monitor),
    path("cm/f5/update/virtual-server", views.cm_f5_update_virtual_server),
    path("cm/f5/task/get/virtual-server", views.cm_f5_get_list_task_create_virtual_server),
    path("cm/f5/task/get/limit-connection", views.cm_f5_get_list_task_limit_connection),
    path("cm/f5/task/update/virtual-server", views.cm_f5_update_task_virtual_server),
    path("cm/f5/task/update/limit-connection", views.cm_f5_update_task_limit_connection),
    path("cm/f5/task/create/virtual-server", views.cm_f5_create_task_virtual_server),
    path("cm/fmc/create-rule", views.cm_fmc_create_rule),
    path("cm/fmc/policy", views.cm_fmc_get_list_policy),
    path("cm/fmc/rule", views.cm_fmc_get_list_rule),
    path("cm/fmc/update/rule-status", views.cm_fmc_update_rule_status),
    path("cm/fmc/update/rule-category", views.cm_fmc_update_rule_category),
    path("cm/fmc/category", views.cm_fmc_get_list_rule_category),
    path("cm/fmc/domain", views.cm_fmc_get_list_domain),
    path("cm/fmc/site", views.cm_fmc_get_list_site),
    path("cm/fmc/gateway", views.cm_fmc_get_list_gateway),
    path("cm/fmc/dashboard-01", views.fmc_dashboard_01),
    path("cm/fmc/dashboard-02", views.fmc_dashboard_02)
]
